# pull official base image
FROM python:3.8-alpine
MAINTAINER Ozzy "ozguryarikkas@gmail.com"

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk add gcc g++ make libffi-dev openssl-dev

# set work directory and copy all files under obmovies
WORKDIR /app
COPY . /app

RUN pip install --upgrade pip
# install dependencies
RUN pip install -r requirements.txt
