# upgrade release if you update this file by:
# helm upgrade mflix-chart mflix-chart --values ./mflix-chart/values.yaml

deployment:
  image: dockerhub_username/mflix_movies
  tag: "b890d6a"

name: mflix
namespace: helm

replicaCount: 3

service:
  port: 5000
  nodePort: 31000

