apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    service: {{ .Values.name }}-service
spec:
  type: NodePort # LoadBalancer   
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
