apiVersion: v1
data:
  .ini: |
    # Ticket: Connection
    # Rename this file to .ini after filling in your MOVIES_DB_URI and your SECRET_KEY
    # Do not surround the URI with quotes

    [PROD]
    SECRET_KEY = super_secret_key_you_should_change
    MOVIES_DB_URI = mongodb+srv://username:<password>@c<your-atlas-cluster-address>?retryWrites=true&w=majority
    MOVIES_NS = sample_mflix
    MONGO_POOLSIZE = 50
    MONGO_TIMEOUTMS = 2500

    [TEST]
    SECRET_KEY = super_secret_testing_key
    MOVIES_DB_URI = your_testing_db_uri (can be the same as Atlas, or a local MongoDB database)
    MOVIES_NS = sample_mflix
    MONGO_POOLSIZE = 50
    MONGO_TIMEOUTMS = 2500
kind: ConfigMap
metadata:
  name: dotini

# Imperative 
# kubectl create configmap dotini --from-file=.ini --dry-run=client -o yaml > ../kubernetes/mflix-configmap.yaml

